site_name: Docs
pages:
- Home: index.md
- Python:
    - Introduction: python/intro.md # editors, versions of python, python prompt, DOS?
    - IPython: python/ipython.md # command prompt
    - Notebooks: python/notebooks.md
    - Virtualenv: python/virtualenv.md
    - Data Structures: python/basics.md # usual stuff, data structures.
    - Functions: python/basics2.md # functions etc.
    - Files: python/basics3.md # files, csv, pdf, etc.
    - Installing Packages: python/pip.md # using pip
    - Objects and Classes: python/classes.md 
    - SQL databases: python/sql.md
    - Web work: python/web.md
    - Science: python/sci.md # numpy, data analysis, matplotlib, biopython
    - GUI: python/gui.md
    - regex: python/regex.md
    - Documentation: python/docs.md
- Web Dev:
    - Web Dev: webdev/webdev.md
- Web Frameworks:
    - Review: webframes/review.md
    - Flask: webframes/flask.md
    - Web2py: webframes/web2py.md
    - Pyramid: webframes/pyramid.md
    - Tornado: webframes/tornado.md
- Django:
    - Intro: django/intro_django.md # 
    - Setting up: django/setting_up.md # installing and first app
    - Models: django/models.md
    - Views: django/views.md
    - Forms: django/forms.md
    - Admin: django/admin.md
    - TDD: django/tdd.md
- Projects:
    - XML Editor: projects/xml_editor.md
    - Renderer: projects/renderer.md
    - Questionnaire: projects/questionnaire.md
    - Other: projects/other.md
theme: mkdocs
